Fixed problems due to pandas having removed append() - replaced with concat()
Full error message:
AttributeError: 'DataFrame' object has no attribute 'append'